### ISSUE TITLE
can use multiple inserts?

### ISSUE THREAD

**Issue by SamZhou99** [ForbesLindesay/sync-mysql#15]
Thanks for your toolkit.
can use multiple inserts?
connection.query("INSERT INTO table(`title`,`content`) VALUES ?", [ ['title', 'content'],[...] ])

**Comment by ForbesLindesay** [comment]
I think you might need to explicilty list out each value:

```js
connection.query("INSERT INTO table(title,content) VALUES (?, ?), (?, ?)", [ ['title A', 'content A'], ['title B', 'content B'] ])
```

but I'm not sure, please do some experimentation and then post here with whatever you find out.

**Comment by SamZhou99** [comment]
No, I need to insert in bulk. Because of this high efficiency
im use require('mysql'), full code is correct.

```js
var mysql = require('mysql');
var pool = mysql.createPool({
    host: '127.0.0.1',
    port: '3306',
    user: 'root',
    password: 'root',
    database: 'test'
});
pool.getConnection(function (err, conn) {
    conn.query("INSERT INTO table_name(name,content) VALUES ?", [[
        ['title A', 'content A'],
        ['title B', 'content B']
    ]], (err, rows) => {
        conn.release();
        console.log(err, rows);
    })
});
```

**Comment by ForbesLindesay** [comment]
You're asking about mysql not sync-mysql. sync-mysql should not be used in environments where performance is a factor.

**Comment by SamZhou99** [comment]
> You're asking about mysql not sync-mysql. sync-mysql should not be used in environments where performance is a factor.

I think there is mysql in your toolkit and it should be supported!
still thank you very much!

**Comment by SamZhou99** [comment]
Request to support bulk inserts again.
Add line 38 of the index.js code to support Array.
Other local parameters don't know if they need to be added, so you can support bulk insert syntax.

line 38 ...... || Array.isArray(arg)

Then please update to npm...

thx u ~~~!!!!

**Comment by ForbesLindesay** [comment]
please submit a pull request if you want that update.
