### ISSUE TITLE
The userid parameter is distorted after the request

### ISSUE THREAD

**Issue by AnimeLore** [ForbesLindesay/sync-mysql#18]
~I use Google translate
After I make a query to mysql, the userid parameter is distorted, meaning instead of 282799894585147392, I get 282799894585147400

**Comment by Gnortius** [comment]
This is a problem mysql itself has, if you're using BIGINT or any type of int for that matter, the number becomes rounded off on the last 3 or so numbers. Just use a VARCHAR or CHAR to store numbers.

**Comment by AnimeLore** [comment]
Thank you!
