### ISSUE TITLE
how to end the connection?

### ISSUE THREAD

**Issue by abid71** [ForbesLindesay/sync-mysql#5]
@ForbesLindesay 
As we can end the connection in all other async based mysql node modules by using the "connection.end()" but in "sync-mysql" we don't know how to end it.

**Comment by ForbesLindesay** [comment]
`connection.dispose()` - https://github.com/ForbesLindesay/sync-mysql#connectiondispose

**Comment by abid71** [comment]
@ForbesLindesay 

Thank you for your support! I have found it by thoroughly checked your main page.
 
Actually, the reason of why I was unable to find it earlier is that "connectiondispose" was written there just as a BOLD TEXT but it should be written in codded form like this 
`connection.dispose()` somewhere in your main readMe, just a suggestion!
