### ISSUE TITLE
is it possibile 'insert into..', and how?  thanks you

### ISSUE THREAD

**Issue by mzambo** [ForbesLindesay/sync-mysql#7]

**Comment by siobhandougall** [comment]
I've just found that this does work, though it doesn't seem to be documented:

```javascript
const result = connection.query('insert into table_name (foo, bar, baz) values (?,?,?)', ['foovalue', 'barvalue', 'bazvalue'])
console.log(result.insertId) // outputs the ID of the inserted row
```

The lowercase 'd' in `insertId` tripped me up for a while, so watch out for that.

**Comment by mzambo** [comment]
Thank you!  But just another question:  I was just wondering how your
module works,
I try to use JS  promise, to sync mysql but without result ...  Your module
really works!

Marco

Il sab 7 lug 2018, 00:40 seandougall <notifications@github.com> ha scritto:

**Comment by ForbesLindesay** [comment]
Yes, the "query" can be anything: an insert statement, an update statement, etc.

N.B. You should **not** use this module in production. In production applications you should use promises. This module is for writing simple scripts, and using in tests.

**Comment by mzambo** [comment]
Do you have an example with js promise ? Becose my promise doesn't work.

Thank you

Il sab 7 lug 2018, 09:54 Forbes Lindesay <notifications@github.com> ha
scritto:

**Comment by ForbesLindesay** [comment]
You can use https://github.com/then/then-mysql (which is the library that this library is based on). If you're using a modern version of node, you can then do:

```js
const MySql = require('then-mysql');

const connection = new MySql({
  host: 'localhost',
  user: 'me',
  passowrd: 'secret'
});

async function run() {
  const result = await connection.query('insert into table_name (foo, bar, baz) values (?,?,?)', ['foovalue', 'barvalue', 'bazvalue']);
  console.log(result.insertId) // outputs the ID of the inserted row
}
run(); // => run returns a `Promise` here, so if you want to wait for it to complete, you must be in an `async` fn and use `await`
```

You can find lots more information about promises in general on https://www.promisejs.org/
